# Change these first
owner: rdp-studio # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: RDPStudio OA 统一认证服务
    url: https://rdpoa.cn.utools.club
  - name: RDPStudio Enc 数据加解密服务
    url: https://rdpenc.cn.utools.club

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.rdpstudio.top
  # baseUrl: /your-repo-name
  name: RDPStudio Status
  introTitle: "RDPStudio 各个服务的在线状态"
  introMessage: "(本站使用 Github Pages 和 Cloudflare Always Online 实现永久访问)"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
